#!/usr/bin/env bash
# world wide web

domain=$1
if [ "$#" -eq 2 ]; then
   sub=$2
else
	sub=("www" "lb-01" "web-01" "web-02")
fi
for subdomain in "${sub[@]}"; do
    echo -n "The subdomain $subdomain"
    dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -n -1 | awk '{ print " is a " $4 " record and points to " $5}'
done
